#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
HOOK_SCRIPT="$SCRIPT_DIR/langfuse-hook.py"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

echo "=== Langfuse Observability for Claude Code ==="
echo ""

# 1. Generate .env with random secrets
if [ -f "$ENV_FILE" ]; then
    echo "[skip] .env already exists. Delete it and re-run to regenerate."
else
    # Prompt for admin credentials
    echo "[setup] Configure your Langfuse admin account."
    echo ""

    read -rp "  Admin email: " ADMIN_EMAIL
    if [ -z "$ADMIN_EMAIL" ]; then
        echo "Error: email cannot be empty."
        exit 1
    fi

    read -rp "  Admin name [Admin]: " ADMIN_NAME
    ADMIN_NAME="${ADMIN_NAME:-Admin}"

    while true; do
        read -rsp "  Admin password (min 12 chars): " ADMIN_PASSWORD
        echo ""
        if [ "${#ADMIN_PASSWORD}" -lt 12 ]; then
            echo "  Password must be at least 12 characters. Try again."
            continue
        fi
        read -rsp "  Confirm password: " ADMIN_PASSWORD_CONFIRM
        echo ""
        if [ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD_CONFIRM" ]; then
            echo "  Passwords do not match. Try again."
            continue
        fi
        break
    done

    echo ""
    echo "[gen]  Generating .env with random secrets..."

    NEXTAUTH_SECRET=$(openssl rand -hex 32)
    ENCRYPTION_KEY=$(openssl rand -hex 32)
    SALT=$(openssl rand -hex 16)
    PG_PASS=$(openssl rand -hex 16)
    CH_PASS=$(openssl rand -hex 16)
    REDIS_PASS=$(openssl rand -hex 16)
    MINIO_PASS=$(openssl rand -hex 16)
    PROJECT_PK="pk-lf-$(openssl rand -hex 12)"
    PROJECT_SK="sk-lf-$(openssl rand -hex 12)"

    # Network mode. Defaults to local (127.0.0.1). For a LAN/Pi deployment,
    # pre-export both before running setup, e.g.:
    #   NEXTAUTH_URL=http://192.168.1.50:3100 LANGFUSE_WEB_BIND=192.168.1.50 ./setup.sh
    # See REMOTE-DEPLOY.md.
    NEXTAUTH_URL_VALUE="${NEXTAUTH_URL:-http://localhost:3100}"
    LANGFUSE_WEB_BIND_VALUE="${LANGFUSE_WEB_BIND:-127.0.0.1}"

    # Fill the template with tools/render_env.py, which writes values
    # literally (sed corrupted values containing & | \) and escapes $ as $$
    # for docker compose. The template is quoted so the shell expands nothing.
    ENV_TEMPLATE="$(mktemp)"
    trap 'rm -f "$ENV_TEMPLATE"' EXIT
    cat > "$ENV_TEMPLATE" <<'ENVEOF'
# Langfuse Self-Hosted Configuration
# Generated by setup.sh — keep this file secure

# === Langfuse Core ===
NEXTAUTH_URL=__NEXTAUTH_URL__
NEXTAUTH_SECRET=__NEXTAUTH_SECRET__
ENCRYPTION_KEY=__ENCRYPTION_KEY__
SALT=__SALT__

# === Network Exposure ===
# 127.0.0.1 = local only. Set to the host LAN IP for LAN/Pi mode (REMOTE-DEPLOY.md).
LANGFUSE_WEB_BIND=__LANGFUSE_WEB_BIND__

# === PostgreSQL ===
POSTGRES_USER=postgres
POSTGRES_PASSWORD=__PG_PASS__
POSTGRES_DB=postgres
DATABASE_URL=postgresql://postgres:__PG_PASS__@postgres:5432/postgres

# === ClickHouse ===
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=__CH_PASS__

# === Redis ===
REDIS_AUTH=__REDIS_PASS__

# === MinIO (S3-compatible storage) ===
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=__MINIO_PASS__
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=__MINIO_PASS__
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=__MINIO_PASS__

# === Initial Setup (auto-creates org, project, and user on first boot) ===
LANGFUSE_INIT_ORG_ID=my-org
LANGFUSE_INIT_ORG_NAME=MyOrg
LANGFUSE_INIT_PROJECT_ID=claude-code
LANGFUSE_INIT_PROJECT_NAME=ClaudeCode
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=__PROJECT_PK__
LANGFUSE_INIT_PROJECT_SECRET_KEY=__PROJECT_SK__
LANGFUSE_INIT_USER_EMAIL=__ADMIN_EMAIL__
LANGFUSE_INIT_USER_NAME=__ADMIN_NAME__
LANGFUSE_INIT_USER_PASSWORD=__ADMIN_PASSWORD__
ENVEOF

    NEXTAUTH_URL="$NEXTAUTH_URL_VALUE" LANGFUSE_WEB_BIND="$LANGFUSE_WEB_BIND_VALUE" \
    NEXTAUTH_SECRET="$NEXTAUTH_SECRET" ENCRYPTION_KEY="$ENCRYPTION_KEY" SALT="$SALT" \
    PG_PASS="$PG_PASS" CH_PASS="$CH_PASS" REDIS_PASS="$REDIS_PASS" MINIO_PASS="$MINIO_PASS" \
    PROJECT_PK="$PROJECT_PK" PROJECT_SK="$PROJECT_SK" \
    ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_NAME="$ADMIN_NAME" ADMIN_PASSWORD="$ADMIN_PASSWORD" \
        python3 "$SCRIPT_DIR/tools/render_env.py" "$ENV_TEMPLATE" "$ENV_FILE"

    echo "       Done."
    echo "       Login:       $ADMIN_EMAIL"
    echo "       Public key:  $PROJECT_PK"
    echo "       Secret key:  $PROJECT_SK"
    echo ""
    echo "       Save your project keys — you'll need them for the hook config."
fi

# 2. Start Langfuse
echo ""
echo "[dock] Starting Langfuse (docker compose up -d)..."
cd "$SCRIPT_DIR"
docker compose up -d

# Health-check and display the URL the dashboard is actually reachable at
# (localhost in local mode, the LAN IP in LAN/Pi mode).
HOST_URL=$(grep '^NEXTAUTH_URL=' "$ENV_FILE" | cut -d= -f2-)
HOST_URL="${HOST_URL:-http://localhost:3100}"

echo ""
echo "[wait] Waiting for Langfuse to be ready..."
for i in $(seq 1 30); do
    if curl -sf -o /dev/null "$HOST_URL"; then
        echo "       Langfuse is up at $HOST_URL"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "       Langfuse not ready after 30s — check: docker compose logs langfuse-web"
        exit 1
    fi
    sleep 1
done

# 3. Read project keys from .env for hook config
PROJECT_PK=$(grep '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$ENV_FILE" | cut -d= -f2)
PROJECT_SK=$(grep '^LANGFUSE_INIT_PROJECT_SECRET_KEY=' "$ENV_FILE" | cut -d= -f2)
ADMIN_EMAIL_DISPLAY=$(grep '^LANGFUSE_INIT_USER_EMAIL=' "$ENV_FILE" | cut -d= -f2)

# 4. Configure Claude Code hook
echo ""
mkdir -p "$HOME/.claude"

# LANGFUSE_HOST is always explicit, so the hook targets the stack this .env
# describes (localhost, or the LAN IP in LAN/Pi mode).
HOOK_ENV="LANGFUSE_HOST=$HOST_URL LANGFUSE_PUBLIC_KEY=$PROJECT_PK LANGFUSE_SECRET_KEY=$PROJECT_SK"
STOP_HOOK_CMD="$HOOK_ENV python3 $HOOK_SCRIPT" \
STOP_FAILURE_HOOK_CMD="$HOOK_ENV python3 $SCRIPT_DIR/session-start-hook.py" \
    python3 "$SCRIPT_DIR/tools/configure_hooks.py" "$CLAUDE_SETTINGS"

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Dashboard:  $HOST_URL"
echo "  Login:      $ADMIN_EMAIL_DISPLAY"
echo "  Hook log:   ~/.claude/langfuse-hook.log"
echo ""
echo "Start a Claude Code conversation — traces will appear automatically."
