#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
HOOK_SCRIPT="$SCRIPT_DIR/langfuse-hook.py"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

echo "=== Langfuse Observability for Claude Code ==="
echo ""

# 1. Generate .env with random secrets
if [ -f "$ENV_FILE" ]; then
    echo "[skip] .env already exists. Delete it and re-run to regenerate."
else
    # Prompt for admin credentials
    echo "[setup] Configure your Langfuse admin account."
    echo ""

    read -rp "  Admin email: " ADMIN_EMAIL
    if [ -z "$ADMIN_EMAIL" ]; then
        echo "Error: email cannot be empty."
        exit 1
    fi

    read -rp "  Admin name [Admin]: " ADMIN_NAME
    ADMIN_NAME="${ADMIN_NAME:-Admin}"

    while true; do
        read -rsp "  Admin password (min 12 chars): " ADMIN_PASSWORD
        echo ""
        if [ "${#ADMIN_PASSWORD}" -lt 12 ]; then
            echo "  Password must be at least 12 characters. Try again."
            continue
        fi
        read -rsp "  Confirm password: " ADMIN_PASSWORD_CONFIRM
        echo ""
        if [ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD_CONFIRM" ]; then
            echo "  Passwords do not match. Try again."
            continue
        fi
        break
    done

    # Prompt for scoring (LLM-as-a-Judge)
    echo ""
    echo "  ┌─────────────────────────────────────────────────────────────┐"
    echo "  │  ⚠  LLM-as-a-Judge Scoring (eval-hook.py)                 │"
    echo "  │                                                             │"
    echo "  │  Scoring uses Claude Haiku to evaluate each conversation    │"
    echo "  │  turn. This incurs additional API costs (~\$0.001/turn).    │"
    echo "  │  You can enable it later by running:                        │"
    echo "  │    python3 eval-hook.py --score                             │"
    echo "  └─────────────────────────────────────────────────────────────┘"
    echo ""
    read -rp "  Enable LLM-as-a-Judge scoring? [y/N]: " ENABLE_SCORING
    ENABLE_SCORING="${ENABLE_SCORING:-n}"

    echo ""
    echo "[gen]  Generating .env with random secrets..."

    NEXTAUTH_SECRET=$(openssl rand -hex 32)
    ENCRYPTION_KEY=$(openssl rand -hex 32)
    SALT=$(openssl rand -hex 16)
    PG_PASS=$(openssl rand -hex 16)
    CH_PASS=$(openssl rand -hex 16)
    REDIS_PASS=$(openssl rand -hex 16)
    MINIO_PASS=$(openssl rand -hex 16)
    PROJECT_PK="pk-lf-$(openssl rand -hex 12)"
    PROJECT_SK="sk-lf-$(openssl rand -hex 12)"

    # Escape $ as $$ in password for docker compose .env compatibility
    ADMIN_PASSWORD_ESCAPED="${ADMIN_PASSWORD//\$/\$\$}"

    # Use quoted heredoc to prevent shell expansion, then substitute with sed
    cat > "$ENV_FILE" <<'ENVEOF'
# Langfuse Self-Hosted Configuration
# Generated by setup.sh — keep this file secure

# === Langfuse Core ===
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=__NEXTAUTH_SECRET__
ENCRYPTION_KEY=__ENCRYPTION_KEY__
SALT=__SALT__

# === PostgreSQL ===
POSTGRES_USER=postgres
POSTGRES_PASSWORD=__PG_PASS__
POSTGRES_DB=postgres
DATABASE_URL=postgresql://postgres:__PG_PASS__@postgres:5432/postgres

# === ClickHouse ===
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=__CH_PASS__

# === Redis ===
REDIS_AUTH=__REDIS_PASS__

# === MinIO (S3-compatible storage) ===
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=__MINIO_PASS__
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=__MINIO_PASS__
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=__MINIO_PASS__

# === Initial Setup (auto-creates org, project, and user on first boot) ===
LANGFUSE_INIT_ORG_ID=my-org
LANGFUSE_INIT_ORG_NAME=MyOrg
LANGFUSE_INIT_PROJECT_ID=claude-code
LANGFUSE_INIT_PROJECT_NAME=ClaudeCode
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=__PROJECT_PK__
LANGFUSE_INIT_PROJECT_SECRET_KEY=__PROJECT_SK__
LANGFUSE_INIT_USER_EMAIL=__ADMIN_EMAIL__
LANGFUSE_INIT_USER_NAME=__ADMIN_NAME__
LANGFUSE_INIT_USER_PASSWORD=__ADMIN_PASSWORD__

# === Scoring (LLM-as-a-Judge) ===
ENABLE_SCORING=__ENABLE_SCORING__
ENVEOF

    # Substitute placeholders (hex-only values are safe for sed; password uses different delimiter)
    sed -i "s|__NEXTAUTH_SECRET__|$NEXTAUTH_SECRET|g" "$ENV_FILE"
    sed -i "s|__ENCRYPTION_KEY__|$ENCRYPTION_KEY|g" "$ENV_FILE"
    sed -i "s|__SALT__|$SALT|g" "$ENV_FILE"
    sed -i "s|__PG_PASS__|$PG_PASS|g" "$ENV_FILE"
    sed -i "s|__CH_PASS__|$CH_PASS|g" "$ENV_FILE"
    sed -i "s|__REDIS_PASS__|$REDIS_PASS|g" "$ENV_FILE"
    sed -i "s|__MINIO_PASS__|$MINIO_PASS|g" "$ENV_FILE"
    sed -i "s|__PROJECT_PK__|$PROJECT_PK|g" "$ENV_FILE"
    sed -i "s|__PROJECT_SK__|$PROJECT_SK|g" "$ENV_FILE"
    sed -i "s|__ADMIN_EMAIL__|$ADMIN_EMAIL|g" "$ENV_FILE"
    sed -i "s|__ADMIN_NAME__|$ADMIN_NAME|g" "$ENV_FILE"
    sed -i "s|__ADMIN_PASSWORD__|$ADMIN_PASSWORD_ESCAPED|g" "$ENV_FILE"
    sed -i "s|__ENABLE_SCORING__|$ENABLE_SCORING|g" "$ENV_FILE"

    echo "       Done."
    echo "       Login:       $ADMIN_EMAIL"
    echo "       Public key:  $PROJECT_PK"
    echo "       Secret key:  $PROJECT_SK"
    echo ""
    echo "       Save your project keys — you'll need them for the hook config."
fi

# 2. Start Langfuse
echo ""
echo "[dock] Starting Langfuse (docker compose up -d)..."
cd "$SCRIPT_DIR"
docker compose up -d

echo ""
echo "[wait] Waiting for Langfuse to be ready..."
for i in $(seq 1 30); do
    if curl -sf -o /dev/null http://localhost:3000; then
        echo "       Langfuse is up at http://localhost:3000"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "       Langfuse not ready after 30s — check: docker compose logs langfuse-web"
        exit 1
    fi
    sleep 1
done

# 3. Read project keys from .env for hook config
PROJECT_PK=$(grep '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$ENV_FILE" | cut -d= -f2)
PROJECT_SK=$(grep '^LANGFUSE_INIT_PROJECT_SECRET_KEY=' "$ENV_FILE" | cut -d= -f2)
ADMIN_EMAIL_DISPLAY=$(grep '^LANGFUSE_INIT_USER_EMAIL=' "$ENV_FILE" | cut -d= -f2)

# 4. Configure Claude Code hook
echo ""
mkdir -p "$HOME/.claude"

HOOK_CMD="LANGFUSE_PUBLIC_KEY=$PROJECT_PK LANGFUSE_SECRET_KEY=$PROJECT_SK python3 $HOOK_SCRIPT"
EVAL_SCRIPT="$SCRIPT_DIR/eval-hook.py"
EVAL_HOOK_CMD="LANGFUSE_PUBLIC_KEY=$PROJECT_PK LANGFUSE_SECRET_KEY=$PROJECT_SK python3 $EVAL_SCRIPT --score"

# Read scoring preference from .env (set during initial setup)
ENABLE_SCORING=$(grep '^ENABLE_SCORING=' "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo "n")

if [ -f "$CLAUDE_SETTINGS" ]; then
    if grep -q "langfuse-hook.py" "$CLAUDE_SETTINGS" 2>/dev/null; then
        # Hook exists — update the command with current keys using python for safe JSON editing
        BACKUP="$CLAUDE_SETTINGS.backup.$(date +%s)"
        cp "$CLAUDE_SETTINGS" "$BACKUP"
        python3 -c "
import json, sys
enable_scoring = '''$ENABLE_SCORING'''.strip().lower().startswith('y')
with open('$CLAUDE_SETTINGS') as f:
    settings = json.load(f)
for hook_group in settings.get('hooks', {}).get('Stop', []):
    hooks = hook_group.get('hooks', [])
    for hook in hooks:
        if 'langfuse-hook.py' in hook.get('command', ''):
            hook['command'] = '''$HOOK_CMD'''
        if 'eval-hook.py' in hook.get('command', ''):
            hook['command'] = '''$EVAL_HOOK_CMD'''
    # Add eval hook if scoring enabled and not already present
    has_eval = any('eval-hook.py' in h.get('command', '') for h in hooks)
    if enable_scoring and not has_eval:
        hooks.append({'type': 'command', 'command': '''$EVAL_HOOK_CMD'''})
    # Remove eval hook if scoring disabled
    if not enable_scoring and has_eval:
        hook_group['hooks'] = [h for h in hooks if 'eval-hook.py' not in h.get('command', '')]
with open('$CLAUDE_SETTINGS', 'w') as f:
    json.dump(settings, f, indent=2)
    f.write('\n')
"
        echo "[hook] Updated hook command with current project keys"
    else
        BACKUP="$CLAUDE_SETTINGS.backup.$(date +%s)"
        cp "$CLAUDE_SETTINGS" "$BACKUP"
        echo "[hook] Backed up existing settings to $BACKUP"
        echo "[hook] Adding Stop hook to $CLAUDE_SETTINGS"
        echo "       You need to manually add the following to your settings.json hooks section:"
        echo ""
        echo '  "Stop": ['
        echo '    {'
        echo '      "hooks": ['
        echo '        {'
        echo '          "type": "command",'
        echo "          \"command\": \"$HOOK_CMD\""
        echo '        }'
        echo '      ]'
        echo '    }'
        echo '  ]'
        echo ""
    fi
else
    echo "[hook] Creating $CLAUDE_SETTINGS with Stop hook..."
    if [[ "$ENABLE_SCORING" =~ ^[Yy] ]]; then
        cat > "$CLAUDE_SETTINGS" <<SETTINGS
{
  "hooks": {
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "$HOOK_CMD"
          },
          {
            "type": "command",
            "command": "$EVAL_HOOK_CMD"
          }
        ]
      }
    ]
  }
}
SETTINGS
        echo "       Created with Stop hook + scoring hook."
    else
        cat > "$CLAUDE_SETTINGS" <<SETTINGS
{
  "hooks": {
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "$HOOK_CMD"
          }
        ]
      }
    ]
  }
}
SETTINGS
        echo "       Created with Stop hook (scoring disabled)."
    fi
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Dashboard:  http://localhost:3000"
echo "  Login:      $ADMIN_EMAIL_DISPLAY"
echo "  Hook log:   ~/.claude/langfuse-hook.log"
if [[ "$ENABLE_SCORING" =~ ^[Yy] ]]; then
    echo "  Scoring:    ENABLED (LLM-as-a-Judge via eval-hook.py)"
    echo "  Eval log:   ~/.claude/langfuse-eval.log"
else
    echo "  Scoring:    DISABLED (enable later: python3 eval-hook.py --score)"
fi
echo ""
echo "Start a Claude Code conversation — traces will appear automatically."
